 '2.1'
services:
  zmq:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    healthcheck:
        test: ["CMD-SHELL", "echo ruok | nc -w 2 zmq 9001"]
        interval: 30s
        timeout: 10s
        retries: 15
  gui:
    image: ashya/rpi-devgui
    ports:
      - "80:5000"
  collector:
    image: ashya/rpi-collector:latest
    ports:
      - "5050:5050"
    depends_on:
      zmq:
        condition: service_healthy
    restart: on-failure
    volumes:
      # persistant storage for our Ashya contracts.
      - /tmp/ashya:/app/contracts
    links:
      - zmq
    environment:
      ZMQ_HOST: zmq

  yolo:
    image: ashya/yolo-pi
    depends_on:
      zmq:
        condition: service_healthy
    environment:
      ZMQ: zmq
    devices:
      - "/dev/video0:/dev/video0"
      
