version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
<<<<<<< HEAD
      - /var/run/docker.sock:/var/run/docker.sock
=======
      - /var/run/docker.sock:/var/run/docker.sock
>>>>>>> 7d24f4dfced74ec2b76fb54ba8486b2ec6eceb9e
