version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
        test: ["CMD-SHELL", "echo ruok | nc -w 2 kafka 9092"]
        interval: 30s
        timeout: 10s
        retries: 15
  gui:
    image: ashya/device-gui 
    ports:
      - "80:5000"
  collector:
    image: ashya/collector
    ports:
      - "5050:5050"
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    volumes:
      # persistant storage for our Ashya contracts.
      - /tmp/ashya:/app/contracts
    links:
      - kafka
    environment:
      KAFKA_HOST: kafka:9092
      
