FROM resin/raspberry-pi-alpine-python:3
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ADD src/* /app/
WORKDIR /app
EXPOSE 5050
CMD [ "python3", "DeviceCollector.py" ]
